version: '3.8'

services:
  selenium:
    image: selenium/standalone-firefox:latest
    ports:
      - '4444:4444'
  app:
    volumes:
      - ./:/app
    build: .
    depends_on:
      - selenium
    ports:
      - '5000:5000'